- module-name: pupil_apriltags
  dlls:
    - from_filenames:
        relative_path: "lib64"
        prefixes:
          - "libapriltag"
          - "apriltag"
    - from_filenames:
        relative_path: "lib"
        prefixes:
          - "libapriltag"
          - "apriltag"
